# tekartik analysis_options extension to pedantic
include: package:tekartik_common_utils/pedantic/analysis_options.strong_mode.yaml

linter:
  rules:
    depend_on_referenced_packages: false

analyzer:
  exclude:
    - build/**
    - out/**