name: tekartik_deploy
version: 0.0.1
description: File deployment helper
dependencies:
  path: any
  pub_semver: any
dev_dependencies:
  test: any
  dev_test: any
  process_run: any
  fs_shim: any
  mustache_no_mirror: any
  resource: any
  fs_shim_test:
    git: git://github.com/tekartik/fs_shim_test.dart
  tekartik_pub:
    git: git://github.com/tekartik/tekartik_pub.dart
dependency_overrides:
#  fs_shim_test:
#    path: /media/ssd/devx/git/github.com/tekartik/fs_shim_test.dart
#  fs_shim:
#    path: /media/ssd/devx/git/github.com/tekartik/fs_shim.dart
executables:
  fsdeploy:
  gsdeploy: