name: tekartik_deploy
version: 0.7.0
description: File deployment helper
homepage: https://github.com/tekartik/deploy.dart
publish_to: none
environment:
  sdk: '>=2.12.0-0 <3.0.0'
dependencies:
  args: '>=1.5.1'
  path: '>=1.6.2'
  pub_semver: '>=1.4.2'
  fs_shim: '>=0.12.0'
  process_run: '>=0.10.3'
  yaml: '>=2.1.15'
  tekartik_io_utils:
    git:
      url: git://github.com/tekartik/io_utils.dart
      ref: null_safety
    version: '>=0.5.2'
dev_dependencies:
  test: any
  dev_test: '>=0.13.2-dev.3'
  tekartik_fs_test:
    git:
      url: git://github.com/tekartik/fs_shim.dart
      path: fs_test
      ref: null_safety
    version: '>=0.1.0'
  tekartik_pub:
    git:
      url: git://github.com/tekartik/pub.dart
      ref: null_safety
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: null_safety
    version: '>=0.1.3'
  tekartik_platform_io:
    git:
      url: git://github.com/tekartik/platform.dart
      path: platform_io
      ref: null_safety
  build_runner: '>=1.1.2'
  build_test: '>=0.10.3+3'

# dependency_overrides:
#  tekartik_common_utils:
#    git:
#      url: git://github.com/tekartik/common_utils.dart
#      ref: dart2
#  process_run:
#    path: /opt/devx/git/github.com/tekartik/process_run.dart
#  fs_shim_test:
#    path: /media/ssd/devx/git/github.com/tekartik/fs_shim_test.dart
#  fs_shim:
#    path: ../fs_shim.dart/fs
#  fs_shim:
#    git: git://github.com/tekartik/fs_shim.dart
