name: tekartik_deploy
version: 0.2.1
description: File deployment helper
homepage: https://github.com/tekartik/deploy.dart
environment:
  sdk: '>=1.20.1 <2.0.0'
dependencies:
  args: '>=0.13.6'
  path: '>=1.4.0'
  pub_semver: '>=1.3.0'
  mustache_no_mirror: any
  fs_shim: '>=0.6.7'
  resource: '>=2.0.2'
  process_run: '>=0.5.0+1'
  yaml: any
  tekartik_io_utils:
    git: git://github.com/tekartik/io_utils.dart
dev_dependencies:
  test: any
  dev_test: any
  fs_shim_test:
    git: git://github.com/tekartik/fs_shim_test.dart
  tekartik_pub:
    git: git://github.com/tekartik/pub.dart
  chrome_travis:
    git: git://github.com/tekartik/chrome_travis.dart
    version: '>=0.1.3'
dependency_overrides:
#  process_run:
#    path: /opt/devx/git/github.com/tekartik/process_run.dart
#  fs_shim_test:
#    path: /media/ssd/devx/git/github.com/tekartik/fs_shim_test.dart
#  fs_shim:
#    path: /media/ssd/devx/git/github.com/tekartik/fs_shim.dart
#  fs_shim:
#    git: git://github.com/tekartik/fs_shim.dart

executables:
  fsdeploy:
  gsdeploy:
  gswebdeploy: