name: tekartik_deploy
version: 0.7.1
description: File deployment helper
homepage: https://github.com/tekartik/deploy.dart
publish_to: none
environment:
  sdk: ^3.7.0
dependencies:
  tekaly_file_download_web:
    git:
      url: https://github.com/tekartikprj/tekaly
      path: packages/file_download_web
      ref: dart3a
  args: ">=2.6.0"
  path: ">=1.9.0"
  pub_semver: ">=2.1.4"
  fs_shim: ">=2.3.3+1"
  process_run: ">=1.2.1+1"
  yaml: ">=3.1.2"
  tekartik_io_utils:
    git:
      url: https://github.com/tekartik/io_utils.dart
      ref: dart3a
    version: '>=0.5.2'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
dev_dependencies:
  test: ">=1.24.0"
  dev_build: ">=1.1.2"
  tekartik_fs_test:
    git:
      url: https://github.com/tekartik/fs_shim.dart
      path: fs_test
      ref: dart3a
    version: '>=0.1.0'
  tekartik_pub:
    git:
      url: https://github.com/tekartik/pub.dart
      ref: dart3a
  tekartik_platform_io:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform_io
      ref: dart3a
  build_runner: ">=2.4.13"
  build_test: '>=0.10.3+3'

dependency_overrides:
#  tekartik_common_utils:
#    git:
#      url: https://github.com/tekartik/common_utils.dart
#      ref: dart2
#  process_run:
#    path: /opt/devx/git/github.com/tekartik/process_run.dart
#  tekartik_fs_test:
#    path: ../fs_shim.dart/fs_test
#  fs_shim:
#    path: ../fs_shim.dart/fs
#  fs_shim:
#    git: https://github.com/tekartik/fs_shim.dart
