name: tekartik_deploy
version: 0.7.1
description: File deployment helper
homepage: https://github.com/tekartik/deploy.dart
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  args: '>=1.5.1'
  path: '>=1.6.2'
  pub_semver: '>=1.4.2'
  fs_shim: '>=2.2.0'
  process_run: '>=0.13.2'
  yaml: '>=2.1.15'
  tekartik_io_utils:
    git:
      url: https://github.com/tekartik/io_utils.dart
      ref: dart3a
    version: '>=0.5.2'
dev_dependencies:
  test: any
  dev_test: '>=0.16.3'
  tekartik_fs_test:
    git:
      url: https://github.com/tekartik/fs_shim.dart
      path: fs_test
      ref: dart3a
    version: '>=0.1.0'
  tekartik_pub:
    git:
      url: https://github.com/tekartik/pub.dart
      ref: dart3a
  tekartik_platform_io:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform_io
      ref: dart3a
  build_runner: '>=1.1.2'
  build_test: '>=0.10.3+3'

dependency_overrides:
#  tekartik_common_utils:
#    git:
#      url: https://github.com/tekartik/common_utils.dart
#      ref: dart2
#  process_run:
#    path: /opt/devx/git/github.com/tekartik/process_run.dart
#  tekartik_fs_test:
#    path: ../fs_shim.dart/fs_test
#  fs_shim:
#    path: ../fs_shim.dart/fs
#  fs_shim:
#    git: https://github.com/tekartik/fs_shim.dart
